name: "Create release"

on:
    workflow_dispatch:
        inputs:
            python_version:
                required: true
                description: "The version of CPython to build"

jobs:
    build:
        name: "Build CPython ${{ inputs.python_version }}"
        runs-on: ubuntu-latest
        container:
            image: "ghcr.io/webassembly/wasi-sdk:wasi-sdk-19"
        steps:
            - name: "Install build dependencies"
              # https://devguide.python.org/getting-started/setup-building/#linux
              # Removed: gdb lcov libffi-dev libncurses5-dev libreadline6-dev tk-dev
              run: |
                apt-get install build-essential pkg-config \
                libbz2-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
                libsqlite3-dev libssl-dev \
                lzma lzma-dev uuid-dev zlib1g-dev
            - name: "Checkout CPython"
              uses: actions/checkout@v3
              with:
                repository: "python/cpython"
                ref: "v${{ inputs.python_version }}"
            - name: "Install CPython"
              uses: actions/setup-python@v4
              with:
                python-version: "3.x"
            - name: "Build"
              run: python3 Tools/wasm/wasm_build.py wasi build

